export const MOCK_BRANCHES = [
    {
        id: "BR-001",
        location: "Manila North",
        accountLimit: 5,
    },
    {
        id: "BR-002",
        location: "Pasig West",
        accountLimit: 3,
    },
    {
        id: "BR-003",
        location: "Quezon City South",
        accountLimit: 10,
    },
    {
        id: "BR-004",
        location: "Makati Central",
        accountLimit: 8,
    },
];

export const MOCK_BRANCH_MANAGERS = [
    {
        id: "USR-1001",
        location: "Manila North",
        email: "ragustin@buybuyin.com",
        firstName: "Rhomer Siegfred S.",
        lastName: "Agustin",
        username: "ragustin_mgr",
    },
    {
        id: "USR-1002",
        location: "Pasig West",
        email: "jbinas@buybuyin.com",
        firstName: "John Benedict S.",
        lastName: "Biñas",
        username: "jbinas_mgr",
    },
    {
        id: "USR-1003",
        location: "Quezon City South",
        email: "zboquiren@buybuyin.com",
        firstName: "Zyryl R.",
        lastName: "Boquiren",
        username: "zboquiren_mgr",
    },
    {
        id: "USR-1004",
        location: "Makati Central",
        email: "mdabocol@buybuyin.com",
        firstName: "María Osiana Buenas",
        lastName: "Dabocol",
        username: "mdabocol_mgr",
    },
    {
        id: "USR-1005",
        location: "Manila North",
        email: "mgatus@buybuyin.com",
        firstName: "Mefiel Ann",
        lastName: "Gatus",
        username: "mgatus_mgr",
    },
    {
        id: "USR-1006",
        location: "Pasig West",
        email: "fmosqueda@buybuyin.com",
        firstName: "Frances S.",
        lastName: "Mosqueda",
        username: "fmosqueda_mgr",
    },
    {
        id: "USR-1007",
        location: "Quezon City South",
        email: "kpabillo@buybuyin.com",
        firstName: "Kenneth D.",
        lastName: "Pabillo",
        username: "kpabillo_mgr",
    },
    {
        id: "USR-1008",
        location: "Makati Central",
        email: "gvalderama@buybuyin.com",
        firstName: "Gabriel V.",
        lastName: "Valderama",
        username: "gvalderama_mgr",
    },
    {
        id: "USR-1009",
        location: "Manila North",
        email: "cvicedo@buybuyin.com",
        firstName: "Christian",
        lastName: "Vicedo",
        username: "cvicedo_mgr",
    },
    {
        id: "USR-1010",
        location: "Pasig West",
        email: "myap@buybuyin.com",
        firstName: "Mark Edwind",
        lastName: "Yap",
        username: "myap_mgr",
    },
    {
        id: "USR-1011",
        location: "Quezon City South",
        email: "ryap@buybuyin.com",
        firstName: "Richard David D.",
        lastName: "Yap",
        username: "ryap_mgr",
    },
];
